### ISSUE TITLE
[ENH]: Be consistent: user parcels instead of atlases.

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#116]
### Are you requiring a new dataset or marker?

- [X] I understand this is not a marker or dataset request

### Which feature do you want to include?

We use them as synonyms, which makes it confusing.

@LeSasse: said to use "parcels".

### How do you imagine this integrated in junifer?

Refactor!

**Comment by LeSasse** [comment]
"parcellation" -> "parcel" is just one ROI
