### ISSUE TITLE
[ENH]: Additional option for `junifer queue` in the CLI

### ISSUE THREAD

**Issue by LeSasse** [juaml/junifer#148]
### Are you requiring a new dataset or marker?

- [X] I understand this is not a marker or dataset request

### Which feature do you want to include?

I would like an option for `junifer queue` to hand over a path under which the `junifer_jobs` directory should appear.
I checked the docs, but from what I can understand this is not yet possible.  

### How do you imagine this integrated in junifer?

In the CLI.

**Comment by fraimondo** [comment]
Why not running `junifer queue` on the directory that you want the jobs to appear?

**Comment by LeSasse** [comment]
I like to wrap calls like this in a shell script in my code directory. The main reason I dont want the `junifer jobs` directory here is that it contains the logs directory, which I would prefer one level up, outside my code directory. But its only a minor quirk of mine, that I can work around.

Still, I think it is nice to have control over the path at which the `junifer _jobs` directory appears.

**Comment by fraimondo** [comment]
The logs directory is inside `junifer_jobs` on purpose. That directory should be self-contained and only administered by junifer. Future features will take care of the logs / queue / etc.

You can change the CWD in your scripts and run `junifer queue`

`cd /path/to/where/I/want && junifer queue /path/to/my/yaml/file`

Sorry about being picky with this one, but junifer is meant to have as less parameters as possible.

**Comment by LeSasse** [comment]
Ah yes, I hadn't thought of that. That will work.

**Comment by synchon** [comment]
@LeSasse Can we close this issue?

**Comment by LeSasse** [comment]
Yes
