### ISSUE TITLE
[DOC]: How to add custom parcellations and friends?

### ISSUE THREAD

**Issue by synchon** [juaml/junifer#166]
### Which element of the documentation do you want to modify and why?

I would like to add my custom parcellation but the docs don't tell you exactly how. So, would be great to have an example.

**Comment by LeSasse** [comment]
I could add an example, if you tell me where to put it maybe @synchon ?

**Comment by fraimondo** [comment]
I guess the `Extending Junifer` section of the docs needs to be improved:

https://juaml.github.io/junifer/main/extending/index.html

**Comment by synchon** [comment]
I would actually create a new subsection under https://juaml.github.io/junifer/main/extending/index.html named as `"Adding parcellations"` and put it there.

**Comment by fraimondo** [comment]
I would create another section named "Adding data", with subsection for masks, parcellations and coordinates.

**Comment by synchon** [comment]
> I would create another section named "Adding data", with subsection for masks, parcellations and coordinates.

My reasoning was due to the fact that we have specific subsections here https://juaml.github.io/junifer/main/builtin.html so one reading the next chapter can connect directly but I am okay with your suggestion as well.

**Comment by fraimondo** [comment]
yes, but I meant in the extending section. In the current doc, it means adding section "6.4: Adding data"

**Comment by synchon** [comment]
> yes, but I meant in the extending section. In the current doc, it means adding section "6.4: Adding data"

Yeah I got that and my reply was based on that. My suggestion:
```
6.4 Adding Parcellations
6.5 Adding Coordinates
6.6 Adding Masks
```

Your suggestion:
```
6.4 Adding data
6.4.1 Adding Parcellations
6.4.2 Adding Coordinates
6.4.3 Adding Masks
```
Right?

**Comment by fraimondo** [comment]
Exactly. I'm fine with any of these options.

**Comment by LeSasse** [comment]
so i can add a file, say `adding_parcellations.rst`, here: https://github.com/juaml/junifer/tree/main/docs/extending

**Comment by synchon** [comment]
> so i can add a file, say `adding_parcellations.rst`, here: https://github.com/juaml/junifer/tree/main/docs/extending

I would keep it as `parcellations.rst` for consistency.
