### ISSUE TITLE
[DOC]: Fix extending datagrabbers section

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#172]
### Which element of the documentation do you want to modify and why?

* Wrong `out` variable (missing `path`)
* Explain better `BOLD_confounds`

**Comment by fraimondo** [comment]
@LeSasse Is this still the case?

**Comment by LeSasse** [comment]
To be honest, I don't remember/understand anymore exactly what the issue was, but quickly looking at the docs it seems to be ok.
