### ISSUE TITLE
[ENH]: Provide mapping between different spaces

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#256]
### Are you requiring a new dataset or marker?

- [X] I understand this is not a marker or dataset request

### Which feature do you want to include?

The dataset usually comes with images in either `native` or a standard space (see #255).

Depending on the markers computed, the subtle differences between spaces might have a significant impact.

The idea is to model the right spaces for masks and parcellations and then warp them.

We will need a repository with all the warping files for all the pair of standard spaces for which we will support warping.

### How do you imagine this integrated in junifer?

1) An on-the-fly downloader for warping files, cached in the junifer/data directory where we download parcellations.
2) Each data type/parcellation/coordinates/masks have one of the standard spaces (see #255).
3) Parcellation, coordinates and masks will have to implement the warping logic.
4) Additionally, the `BOLDWarper` preprocessor should be capable of handling standard spaces as `reference`.

**Comment by synchon** [comment]
Addressed in #297
