### ISSUE TITLE
[DOC]: Update "Adding Masks" example code 

### ISSUE THREAD

**Issue by tomug** [juaml/junifer#290]
### Which element of the documentation do you want to modify and why?

In the current version of the code example in the Documentation under "7.6.1. Step 1: Prepare code to register a mask" imports the "register_mask"(current name according to GitHub repo of Junifer) function as "register_custom_mask"(name in doc).

**Comment by synchon** [comment]
Hi, thanks for reporting. Would you like to open a PR for the correction? 🙃
