### ISSUE TITLE
[DOC] Update the documentation with a list of existing datasets

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#31]
1) Complete the table in documentation regarding datagrabbers, indicating which datasets are under consideration, which are implemented.
2) Create a dataset-request issue for each dataset (don't forget to set project, status Todo, subject "Data")

**Comment by synchon** [comment]
@fraimondo Can we close this?

**Comment by synchon** [comment]
Broadcast ping 🤖

**Comment by synchon** [comment]
In my opinion, this was solved, hence closing. Please re-open if necessary.
