### ISSUE TITLE
[ENH]: UKB gray matter template

### ISSUE THREAD

**Issue by kaurao** [juaml/junifer#334]
### Are you requiring a new dataset or marker?

- [X] I understand this is not a marker or dataset request

### Which feature do you want to include?

Add support for UKB gray matter template. It is available for download: https://open.win.ox.ac.uk/pages/douaud/ukb-lifo-flica/
Direct link: https://www.fmrib.ox.ac.uk/datasets/UKB_LIFO_FLICA/UKB_15K_GM_template.nii.gz

### How do you imagine this integrated in junifer?

This template should be available as an option perhaps with name `UKB_15K_GM`.

**Comment by synchon** [comment]
@kaurao Is it ok if we have it as a mask with junifer, as it's just for the GM?

**Comment by kaurao** [comment]
This can be used as a "general" GM mask and not only when extracting markers from GM. Thanks!
