### ISSUE TITLE
[MARKER]: connectedness

### ISSUE THREAD

**Issue by kaurao** [juaml/junifer#34]
### Which marker do you want to include?

Functional connectedness. 
This is a "new" marker that we have developed.
Inputs: 
3D list of coordinates in MNI space
sphere size
whole-brain (GM) mask

Outputs:
An array with number of elemnts euql to the length of the coordinates list

### Is there any publication or available code?

No publication but there is custom MATLAB code.

**Comment by fraimondo** [comment]
Closing, as this is now implemented in the juni-private-farm and will be moved to the juni-farm at some point in the future.
