### ISSUE TITLE
[DAT]: Add CamCAN dataset

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#46]
### Which dataset is it?

CamCAN dataset for Juseless

### Implementation

Did not implement anything

### Dataset access restrictions

- [ ] Public and open access (no registration)
- [ ] Public and open access (registration required)
- [X] Restricted access (needs approuval)
- [X] Available only in specific locations (Juseless, Jureca)

**Comment by LeSasse** [comment]
I can work on this one if nobody else has started yet @fraimondo?

**Comment by fraimondo** [comment]
@verakye tried, but it was a complex one. @LeSasse Maybe with your knowledge on HCP and AOMIC PIOP1/2 you can tackle this one too.

**Comment by LeSasse** [comment]
Yes, I think there are two main problems to tackle:

1. The authentication process is sometimes a bit problematic from what I remember.
2. The confound files are in .mat files with that new pesty 7.3 version. 

I will focus on UCLA first, then do this one.

**Comment by LeSasse** [comment]
Another option would be to fmriprep the original camcan dataset for which I made some testing code here a while ago (https://github.com/juaml/fmriprep_camcan). We could then set that up as a datalad dataset on juseless ourselves, but this would be good to coordinate with others as well.

**Comment by LeSasse** [comment]
In terms of reading mat7.3 files in python, I have used this package in the past, so maybe their code will be useful in implementing this in junifer: https://pypi.org/project/mat73/

**Comment by verakye** [comment]
> @verakye tried, but it was a complex one. @LeSasse Maybe with your knowledge on HCP and AOMIC PIOP1/2 you can tackle this one too.

@LeSasse, @fraimondo I didn't try the CamCAN so far because of authentication issues (I didn't have access). I started with Enki which is a bit irritating/complex, but initial stuff is set up.
