### ISSUE TITLE
[DAT]: Add IXI dataset

### ISSUE THREAD

**Issue by fraimondo** [juaml/junifer#48]
### Which dataset is it?

IXI dataset for Juseless

### Implementation

Did not implement anything

### Dataset access restrictions

- [ ] Public and open access (no registration)
- [ ] Public and open access (registration required)
- [X] Restricted access (needs approuval)
- [X] Available only in specific locations (Juseless, Jureca)

**Comment by LeSasse** [comment]
As far as I can tell in terms of processed IXI data, we have only the "VBM_GM" type ("m0wp1sub-{subject}.nii.gz"). The elements for this dataset consist of two replacements, i.e. 'site' (site of scan; "Guys", "HH", "IOP") and subject id. This I should be able to implement relatively easily similar to the DataladJuselessUKBVBM class. Let me know if I am missing something here @fraimondo @kaurao that you had in mind.

**Comment by fraimondo** [comment]
@LeSasse : then there are two datasets that can be interpreted as IXI

This if from then inm-docs:

IXI
The [IXI](https://brain-development.org/ixi-dataset) dataset contains nearly 600 MR images from normal, healthy subjects. The data has been collected at three different hospitals in London; Hammersmith Hospital using a Philips 3T system, Guy’s Hospital using a Philips 1.5T system, and the Institute of Psychiatry using a GE 1.5T system. The MR image acquisition protocol for each subject includes T1, T2 and PD-weighted images, MRA images, and diffusion-weighted images (15 directions).

Then we might have the VBM data processed, but it should be two different datasets then.

@kaurao any help here? Who's using these datasets?

**Comment by LeSasse** [comment]
Yes, fair enough, I can make another datagrabber for the original dataset which has T1w, T2w, and DWI data. I am not sure how they fit in with the rest of the junifer pipeline/whether they need any further processing, but we can at least make them available.

**Comment by fraimondo** [comment]
> Yes, fair enough, I can make another datagrabber for the original dataset which has T1w, T2w, MRA and DWI data. I am not sure how they fit in with the rest of the junifer pipeline/whether they need any further processing, but we can at least make them available.

Lets wait for @kaurao on this one. It does not make any sense (for the moment) to have unprocessed data that can't be used with junifer. The only reason would be to allow people to use the datagrabber for their python code.... not a priority right now

**Comment by kaurao** [comment]
many are using CAT output of this dataset (Shammi, Georgios, Nico). Basically this is a goto dataset for any T1 related project, but having grabber for raw data won't be really useful.

**Comment by LeSasse** [comment]
Ok, in that case I can make a datagrabber for CAT output, and we implement whatever else we need in the future ... in the future.

**Comment by fraimondo** [comment]
Then this means another dataset in `juseless`. I will then do a refactor as this is growing fast.

**Comment by LeSasse** [comment]
makes sense to me, especially since there is a lot of small but separate datasets for juseless. For IXI, I have the class + tests implemented, so let me know and and where I should put it once you have done the refactor.

**Comment by fraimondo** [comment]
wait for #100 to be merged
