### ISSUE TITLE
[MARKER]: ETS_RSS 

### ISSUE THREAD

**Issue by kaurao** [juaml/junifer#51]
### Which marker do you want to include?

edge-wise time-series RSS values

Inputs:
4D nifti, processed (e.g. GS regression)

Output:
An array of length of number of time-points

### Is there any publication or available code?

https://www.pnas.org/doi/10.1073/pnas.2005531117

### Do you have a sample code that implements this outside of junifer?

```shell
@leo
```

**Comment by LeSasse** [comment]
To double check, it is assumed that the input needs no more processing, right? I simply take the nifti.dataobj, and do the steps to obtain the ETS from this @kaurao?
