### ISSUE TITLE
[BUG]: Change type "confound" to "BOLD_confound" in preprocessing for consistency with data grabber

### ISSUE THREAD

**Issue by verakye** [juaml/junifer#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The `types` naming in the preprocessing and the data grabbing has to be consistent. In the data grabbing the "desc-confounds_regressors" from fmriprep are currently names as `BOLD_confounds` but in the preprocessing this is referred to as `confounds`. 

### Expected Behavior

The above described naming has to be adapted in the preprocessing for consistency.

### Steps To Reproduce

-

### Environment

```markdown
Environment as specified in the repos `condo-env.yml`.
```

**Comment by fraimondo** [comment]
addressed in #111
