### ISSUE TITLE
[DAT]: AOMIC PIOP1 and PIOP2

### ISSUE THREAD

**Issue by LeSasse** [juaml/junifer#94]
### Which dataset is it?

For the [AOMIC](https://nilab-uva.github.io/AOMIC.github.io/) dataset so far the [ID1000 datagrabber](https://github.com/juaml/junifer/blob/main/junifer/datagrabber/aomic1000.py) is implemented by @verakye. We would like to use the [PIOP1](https://openneuro.org/datasets/ds002785) and [PIOP2](https://openneuro.org/datasets/ds002790/versions/2.0.0) datasets as well through junifer.

### Implementation

It can be implemented very similarly to Vera's AOMIC1000 datagrabber. I can implement the PIOP1 and PIOP2 datagrabbers based on that.

### Dataset access restrictions

- [X] Public and open access (no registration)
- [ ] Public and open access (registration required)
- [ ] Restricted access (needs approuval)
- [ ] Available only in specific locations (Juseless, Jureca)

**Comment by LeSasse** [comment]
@fraimondo @synchon @verakye before i start working on these, there are two options:
1. Either I implement these datagrabbers as separate classes.
2. Or I take the existing AOMIC class and add a dataset parameter in init, so it can be initialised by name i.e. using "id1000", "piop1", "piop2", and then the individual elements and patterns depend on that initialisation.

Which option do you think is better/more consistent with junifer?

**Comment by fraimondo** [comment]
I think the best option would be option 1.

From this image, it seems that they are 3 independent datasets, each with different tasks and sequences. Having them all together will add parameters to the [aomic1000](https://github.com/juaml/junifer/blob/main/junifer/datagrabber/aomic1000.py) datagrabber. This is something we are trying to avoid with junifer.

Also, follow the same logic as with the HCP datagrabber. Tasks can be part of the constructor, but they are also part of the `__getitem__` method.

Can you also do #95 on this one? It would be a good idea to create a package `aomic` under `junifer.datagrabber` and place the 3 aomic datasets there.

![figure_1](https://user-images.githubusercontent.com/4493699/193997932-e9126866-527d-4cbe-9bee-111f116e3124.png)

**Comment by LeSasse** [comment]
> I think the best option would be option 1.
> 
> From this image, it seems that they are 3 independent datasets, each with different tasks and sequences. Having them all together will add parameters to the [aomic1000](https://github.com/juaml/junifer/blob/main/junifer/datagrabber/aomic1000.py) datagrabber. This is something we are trying to avoid with junifer.
> 
> Also, follow the same logic as with the HCP datagrabber. Tasks can be part of the constructor, but they are also part of the `__getitem__` method.
> 
> Can you also do #95 on this one? It would be a good idea to create a package `aomic` under `junifer.datagrabber` and place the 3 aomic datasets there.
> 
> ![figure_1](https://user-images.githubusercontent.com/4493699/193997932-e9126866-527d-4cbe-9bee-111f116e3124.png)

Yes, I agree with this after some thinking also. I will do #95 as well. Thanks for the quick response!
